export enum TokenType {
  // Literals
  NUMBER = 'NUMBER',
  STRING = 'STRING',
  IDENTIFIER = 'IDENTIFIER',
  BOOLEAN = 'BOOLEAN',
  NIL = 'NIL',

  // Keywords
  FUNCTION = 'FUNCTION',
  END = 'END',
  IF = 'IF',
  THEN = 'THEN',
  ELSE = 'ELSE',
  ELSEIF = 'ELSEIF',
  WHILE = 'WHILE',
  DO = 'DO',
  FOR = 'FOR',
  IN = 'IN',
  REPEAT = 'REPEAT',
  UNTIL = 'UNTIL',
  RETURN = 'RETURN',
  LOCAL = 'LOCAL',
  TRUE = 'TRUE',
  FALSE = 'FALSE',
  NIL_KEYWORD = 'NIL_KEYWORD',
  AND = 'AND',
  OR = 'OR',
  NOT = 'NOT',
  BREAK = 'BREAK',
  CONTINUE = 'CONTINUE',
  CLASS = 'CLASS',
  NEW = 'NEW',
  IMPORT = 'IMPORT',
  METHOD = 'METHOD',
  THIS = 'THIS',
  SELF = 'SELF',

  // Operators
  PLUS = 'PLUS',
  MINUS = 'MINUS',
  STAR = 'STAR',
  SLASH = 'SLASH',
  PERCENT = 'PERCENT',
  EQUAL = 'EQUAL',
  EQUAL_EQUAL = 'EQUAL_EQUAL',
  BANG = 'BANG',
  BANG_EQUAL = 'BANG_EQUAL',
  LESS = 'LESS',
  GREATER = 'GREATER',
  LESS_EQUAL = 'LESS_EQUAL',
  GREATER_EQUAL = 'GREATER_EQUAL',
  DOT = 'DOT',
  DOT_DOT = 'DOT_DOT',
  COMMA = 'COMMA',
  COLON = 'COLON',
  SEMICOLON = 'SEMICOLON',
  LPAREN = 'LPAREN',
  RPAREN = 'RPAREN',
  LBRACKET = 'LBRACKET',
  RBRACKET = 'RBRACKET',
  LBRACE = 'LBRACE',
  RBRACE = 'RBRACE',
  ASSIGN = 'ASSIGN',
  HASH = 'HASH',
  AMPERSAND = 'AMPERSAND',
  PIPE = 'PIPE',
  TILDE = 'TILDE',
  BIT_LSHIFT = 'BIT_LSHIFT',
  BIT_RSHIFT = 'BIT_RSHIFT',
  PLUS_EQUAL = 'PLUS_EQUAL',
  MINUS_EQUAL = 'MINUS_EQUAL',
  STAR_EQUAL = 'STAR_EQUAL',
  SLASH_EQUAL = 'SLASH_EQUAL',
  PERCENT_EQUAL = 'PERCENT_EQUAL',

  // Special
  EOF = 'EOF',
  NEWLINE = 'NEWLINE',
  COMMENT = 'COMMENT',
}

export interface Token {
  type: TokenType;
  lexeme: string;
  literal: any;
  line: number;
  column: number;
}

export const KEYWORDS: Record<string, TokenType> = {
  'function': TokenType.FUNCTION,
  'end': TokenType.END,
  'if': TokenType.IF,
  'then': TokenType.THEN,
  'else': TokenType.ELSE,
  'elseif': TokenType.ELSEIF,
  'while': TokenType.WHILE,
  'do': TokenType.DO,
  'for': TokenType.FOR,
  'in': TokenType.IN,
  'repeat': TokenType.REPEAT,
  'until': TokenType.UNTIL,
  'return': TokenType.RETURN,
  'local': TokenType.LOCAL,
  'true': TokenType.TRUE,
  'false': TokenType.FALSE,
  'nil': TokenType.NIL_KEYWORD,
  'and': TokenType.AND,
  'or': TokenType.OR,
  'not': TokenType.NOT,
  'break': TokenType.BREAK,
  'continue': TokenType.CONTINUE,
  'class': TokenType.CLASS,
  'new': TokenType.NEW,
  'import': TokenType.IMPORT,
  'method': TokenType.METHOD,
  'this': TokenType.THIS,
  'self': TokenType.SELF,
};