export enum Opcode {
  NOP = 0,
  PUSH = 1,
  POP = 2,
  ADD = 3,
  SUB = 4,
  MUL = 5,
  DIV = 6,
  MOD = 7,
  NEG = 8,
  EQ = 9,
  NEQ = 10,
  LT = 11,
  GT = 12,
  LTE = 13,
  GTE = 14,
  AND = 15,
  OR = 16,
  NOT = 17,
  JMP = 18,
  JZ = 19,
  JNZ = 20,
  CALL = 21,
  RET = 22,
  LOAD = 23,
  STORE = 24,
  LOAD_GLOBAL = 25,
  STORE_GLOBAL = 26,
  NEW_TABLE = 27,
  NEW_ARRAY = 28,
  INDEX_GET = 29,
  INDEX_SET = 30,
  NATIVE_CALL = 31,
  HALT = 32,
  NEW_STRING = 33,
  NEW_NUMBER = 34,
  NEW_BOOL = 35,
  NEW_NIL = 36,
  DUP = 37,
  SWAP = 38,
  LOAD_CONST = 39,
  PRINT = 40,
  MAKE_FUNCTION = 41,
  CLOSURE = 42,
  GET_UPVALUE = 43,
  SET_UPVALUE = 44,
  CLOSE_UPVALUE = 45,
  CLASS = 46,
  NEW_OBJECT = 47,
  LOAD_FIELD = 48,
  STORE_FIELD = 49,
  METHOD_CALL = 50,
  FOR_PREP = 51,
  FOR_LOOP = 52,
  TFOR_LOOP = 53,
  SET_LIST = 54,
  CONCAT = 55,
  LEN = 56,
}

export const OPCODE_NAMES: Record<number, string> = {
  [Opcode.NOP]: 'NOP',
  [Opcode.PUSH]: 'PUSH',
  [Opcode.POP]: 'POP',
  [Opcode.ADD]: 'ADD',
  [Opcode.SUB]: 'SUB',
  [Opcode.MUL]: 'MUL',
  [Opcode.DIV]: 'DIV',
  [Opcode.MOD]: 'MOD',
  [Opcode.NEG]: 'NEG',
  [Opcode.EQ]: 'EQ',
  [Opcode.NEQ]: 'NEQ',
  [Opcode.LT]: 'LT',
  [Opcode.GT]: 'GT',
  [Opcode.LTE]: 'LTE',
  [Opcode.GTE]: 'GTE',
  [Opcode.AND]: 'AND',
  [Opcode.OR]: 'OR',
  [Opcode.NOT]: 'NOT',
  [Opcode.JMP]: 'JMP',
  [Opcode.JZ]: 'JZ',
  [Opcode.JNZ]: 'JNZ',
  [Opcode.CALL]: 'CALL',
  [Opcode.RET]: 'RET',
  [Opcode.LOAD]: 'LOAD',
  [Opcode.STORE]: 'STORE',
  [Opcode.LOAD_GLOBAL]: 'LOAD_GLOBAL',
  [Opcode.STORE_GLOBAL]: 'STORE_GLOBAL',
  [Opcode.NEW_TABLE]: 'NEW_TABLE',
  [Opcode.NEW_ARRAY]: 'NEW_ARRAY',
  [Opcode.INDEX_GET]: 'INDEX_GET',
  [Opcode.INDEX_SET]: 'INDEX_SET',
  [Opcode.NATIVE_CALL]: 'NATIVE_CALL',
  [Opcode.HALT]: 'HALT',
  [Opcode.NEW_STRING]: 'NEW_STRING',
  [Opcode.NEW_NUMBER]: 'NEW_NUMBER',
  [Opcode.NEW_BOOL]: 'NEW_BOOL',
  [Opcode.NEW_NIL]: 'NEW_NIL',
  [Opcode.DUP]: 'DUP',
  [Opcode.SWAP]: 'SWAP',
  [Opcode.LOAD_CONST]: 'LOAD_CONST',
  [Opcode.PRINT]: 'PRINT',
  [Opcode.MAKE_FUNCTION]: 'MAKE_FUNCTION',
  [Opcode.CLOSURE]: 'CLOSURE',
  [Opcode.GET_UPVALUE]: 'GET_UPVALUE',
  [Opcode.SET_UPVALUE]: 'SET_UPVALUE',
  [Opcode.CLOSE_UPVALUE]: 'CLOSE_UPVALUE',
  [Opcode.CLASS]: 'CLASS',
  [Opcode.NEW_OBJECT]: 'NEW_OBJECT',
  [Opcode.LOAD_FIELD]: 'LOAD_FIELD',
  [Opcode.STORE_FIELD]: 'STORE_FIELD',
  [Opcode.METHOD_CALL]: 'METHOD_CALL',
  [Opcode.FOR_PREP]: 'FOR_PREP',
  [Opcode.FOR_LOOP]: 'FOR_LOOP',
  [Opcode.TFOR_LOOP]: 'TFOR_LOOP',
  [Opcode.SET_LIST]: 'SET_LIST',
  [Opcode.CONCAT]: 'CONCAT',
  [Opcode.LEN]: 'LEN',
};